development:
  adapter: postgresql
  database: ritly_review_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: ritly_review_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ritly_review_prod
  pool: 5
  timeout: 5000
